version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
    - "postgres"
    - "postgres_test"
    environment:
    - DATABASE_URL=postgres://postgres:555666@postgres:5432/postgres
    - NODE_ENV=development_docker
  postgres:
    image: 'postgres:9.6.8-alpine'
    environment:
      POSTGRES_PASSWORD: 555666
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - '54321:5432'
  postgres_test:
    image: 'postgres:9.6.8-alpine'
    environment:
      POSTGRES_PASSWORD: 555666
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5000:5432"
