version: "3"
services:
  app:
    environment:
    - DATABASE_URL=postgres://postgres:555666@postgres_test:5432/postgres
    - NODE_ENV=test_docker
    command: bash -c "sleep 5 && npm run migration && sleep 2 && npm run test"
