version: '3'
services:
  postgres:
    image: 'postgres:9.6.8-alpine'
    environment:
      POSTGRES_PASSWORD: 555666
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - '5000:5432'
  postgres_test:
    image: 'postgres:9.6.8-alpine'
    environment:
      POSTGRES_PASSWORD: 555666
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5001:5432"
  app:
    build: .
    depends_on:
    - postgres
    ports:
    - '3000:3000'
    links:
    - "postgres"
    - "postgres_test"
    environment:
    - DATABASE_URL=postgres://postgres:555666@postgres:5432/postgres
    - NODE_ENV=development_docker
    command: bash -c "sleep 5 && npm run migration && sleep 2 && npm start"
